version: '2'
services:

    varnish:
        image: million12/varnish
        ports:
            - "80:80"
        environment:
            VCL_CONFIG: /data/webservers.vcl
        volumes:
            - ./varnish:/data
        links:
            - web

    web:
        image: richarvey/nginx-php-fpm
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
